# Generated by Django 4.2.5 on 2023-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('subtotal_carrito', models.FloatField()),
                ('estado', models.SmallIntegerField(default=0, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
