# Generated by Django 4.2.5 on 2023-09-12 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferreteria', '0002_categoria_detallepedido_marca_tipoenvio_tipopago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(max_length=255, null=True, upload_to='USUARIOS_ADMIN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
