# Generated by Django 4.2.5 on 2023-09-12 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferreteria', '0003_usuarioadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'tipos de movimiento',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='alerta_existencia',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido_pedido', to='ferreteria.pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido_producto', to='ferreteria.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='detalle_pedido', through='ferreteria.DetallePedido', to='ferreteria.producto'),
        ),
        migrations.AlterField(
            model_name='usuarioadmin',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='USUARIOS_ADMIN'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.SmallIntegerField(choices=[(0, 'Completado'), (1, 'En espera'), (2, 'Anulado')], default=0)),
                ('productos', models.ManyToManyField(related_name='detalle_movimiento', through='ferreteria.DetalleMovimiento', to='ferreteria.producto')),
                ('tipomovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_tipo', to='ferreteria.tipomovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_movimiento_movimiento', to='ferreteria.movimiento'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_movimiento_producto', to='ferreteria.producto'),
        ),
    ]
