# Generated by Django 4.2.5 on 2023-09-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0004_detallemovimiento_tipomovimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaproducto',
            options={'verbose_name': 'metadata producto', 'verbose_name_plural': 'metadata productos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'pedidos'},
        ),
    ]
