# Generated by Django 4.2.5 on 2023-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0007_alter_cliente_subtotal_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=255, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='subtotal_carrito',
            field=models.FloatField(default=0),
        ),
    ]
