# Generated by Django 4.2.5 on 2023-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0008_alter_cliente_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_destacada',
            field=models.ImageField(max_length=255, null=True, upload_to='CATEGORIAS'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen_destacada',
            field=models.ImageField(max_length=255, null=True, upload_to='MARCAS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_destacada',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='PRODUCTOS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='mas_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='miniatura',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='PRODUCTOS'),
        ),
    ]
