# Generated by Django 3.2.17 on 2023-09-26 22:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ferreteria', '0009_categoria_imagen_destacada_marca_imagen_destacada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
