# Generated by Django 4.2.5 on 2023-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0013_producto_stripe_id_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
