# Generated by Django 4.2.5 on 2023-10-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0014_alter_producto_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='app_user',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ferreteria.pedido'),
            preserve_default=False,
        ),
    ]
