# Generated by Django 4.2.5 on 2023-10-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0015_remove_userpayment_app_user_userpayment_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descuento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Recibido'), (1, 'Procesando'), (2, 'Pendiente de pago'), (3, 'Enviado'), (4, 'Entregado')], default=0),
        ),
    ]
