# Generated by Django 4.2.5 on 2023-10-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0016_alter_pedido_descuento_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoenvio',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipoenvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_tipoenvio', to='ferreteria.tipoenvio'),
        ),
    ]
