# Generated by Django 4.2.5 on 2023-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0017_tipoenvio_stripe_id_alter_pedido_tipoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stripe_id_descuento',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='CATEGORIAS'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_destacada',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='CATEGORIAS'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='icono',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='MARCAS'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen_destacada',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='MARCAS'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='ferreteria.categoria'),
        ),
    ]
