# Generated by Django 4.2.5 on 2023-10-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0018_producto_stripe_id_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ferreteria.marca'),
        ),
    ]
