# Generated by Django 4.2.5 on 2023-10-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0019_alter_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Disponible'), (1, 'Eliminado')], default=0),
        ),
    ]
