# Generated by Django 4.2.5 on 2023-10-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0020_ubicacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='estado',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
