# Generated by Django 4.2.5 on 2023-10-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0021_remove_movimiento_estado_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipomovimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_tipo', to='ferreteria.tipomovimiento', verbose_name='Tipo de movimiento'),
        ),
    ]
