# Generated by Django 4.2.5 on 2023-10-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0022_movimiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoenvio',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Recibido'), (1, 'Procesando'), (2, 'Pendiente de pago'), (3, 'Enviado'), (4, 'Entregado'), (5, 'Cancelado')], default=0),
        ),
    ]
